from __future__ import annotations

from collections import Counter
from typing import Any


MANIFEST_VERSION = "phase-16"
MANIFEST_SOURCE = "docs/COMPATIBILITY.md"


FEATURES: list[dict[str, Any]] = [
    {
        "id": "endpoints.responses.create",
        "category": "endpoint",
        "surface": "POST /v1/responses",
        "status": "supported",
        "tags": ["core", "state"],
        "benchmark_case": "responses.blocking",
    },
    {
        "id": "endpoints.responses.retrieve",
        "category": "endpoint",
        "surface": "GET /v1/responses/{response_id}",
        "status": "supported",
        "tags": ["core", "state"],
        "benchmark_case": "responses.retrieve",
    },
    {
        "id": "endpoints.responses.delete",
        "category": "endpoint",
        "surface": "DELETE /v1/responses/{response_id}",
        "status": "supported",
        "tags": ["core", "state"],
        "benchmark_case": "responses.delete",
    },
    {
        "id": "endpoints.responses.input_items",
        "category": "endpoint",
        "surface": "GET /v1/responses/{response_id}/input_items",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.input_items",
    },
    {
        "id": "endpoints.responses.artifact_content",
        "category": "endpoint",
        "surface": "GET /v1/responses/{response_id}/artifacts/{artifact_id}/content",
        "status": "supported_local",
        "tags": ["multimodal", "state"],
        "benchmark_case": "responses.input_file.file_id",
        "notes": "Downloads tenant-scoped local response artifact text content created from input_file normalization.",
    },
    {
        "id": "endpoints.responses.artifacts",
        "category": "endpoint",
        "surface": "GET /v1/responses/{response_id}/artifacts",
        "status": "supported_local",
        "tags": ["multimodal", "state"],
        "benchmark_case": "responses.include.annotations",
        "notes": "Lists tenant-scoped local response artifact metadata with after/before cursors.",
    },
    {
        "id": "state.input_item_storage",
        "category": "state",
        "surface": "stored response input items with stable item IDs and original order",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.items.input_storage",
    },
    {
        "id": "state.input_item_pagination",
        "category": "state",
        "surface": "input item pagination with after, before, limit, order, first_id, last_id, has_more",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.items.pagination_after",
    },
    {
        "id": "state.files_pagination",
        "category": "state",
        "surface": "Files API pagination with after, limit, order, first_id, last_id, has_more",
        "status": "supported_local",
        "tags": ["files", "state", "sdk"],
        "benchmark_case": "sdk.responses.create_retrieve_delete",
    },
    {
        "id": "state.input_items_store_false_hidden",
        "category": "state",
        "surface": "store=false responses do not expose input item lists",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.items.store_false_hidden",
    },
    {
        "id": "state.input_items_tenant_scope",
        "category": "state",
        "surface": "stored input item lists are tenant-scoped",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.items.tenant_scope",
    },
    {
        "id": "endpoints.responses.input_tokens",
        "category": "endpoint",
        "surface": "POST /v1/responses/input_tokens",
        "status": "supported_estimated",
        "tags": ["core", "context"],
        "benchmark_case": "responses.input_tokens.model_aware",
    },
    {
        "id": "endpoints.responses.cancel",
        "category": "endpoint",
        "surface": "POST /v1/responses/{response_id}/cancel",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.cancel",
        "notes": "Cancels background Responses jobs in the current single Respawn instance.",
    },
    {
        "id": "endpoints.responses.compact",
        "category": "endpoint",
        "surface": "POST /v1/responses/compact",
        "status": "supported_local",
        "tags": ["context", "state"],
        "benchmark_case": "responses.compact",
        "notes": "Returns a response.compaction object with a local opaque compaction item and deterministic token accounting.",
    },
    {
        "id": "endpoints.chat_completions.create",
        "category": "endpoint",
        "surface": "POST /v1/chat/completions",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "chat.completions",
    },
    {
        "id": "endpoints.models.list",
        "category": "endpoint",
        "surface": "GET /v1/models",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "models",
    },
    {
        "id": "endpoints.files.create_retrieve_delete",
        "category": "endpoint",
        "surface": "POST/GET/DELETE /v1/files and GET /v1/files/{file_id}/content",
        "status": "supported_local",
        "tags": ["files", "state"],
        "benchmark_case": "files.create_retrieve_delete",
        "notes": "Implements the local Files API subset needed by Responses file_id inputs, with tenant scope, quota, TTL, and database/filesystem storage backends.",
    },
    {
        "id": "request.model_and_text_input",
        "category": "request_field",
        "surface": "model, input string, input text parts",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.blocking",
    },
    {
        "id": "request.instructions",
        "category": "request_field",
        "surface": "instructions",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.structured_output",
    },
    {
        "id": "request.previous_response_id",
        "category": "request_field",
        "surface": "previous_response_id",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.previous_response_id",
    },
    {
        "id": "request.store",
        "category": "request_field",
        "surface": "store",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.store_false",
    },
    {
        "id": "request.stream",
        "category": "request_field",
        "surface": "stream",
        "status": "supported",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.lifecycle_text",
    },
    {
        "id": "request.stream_options",
        "category": "request_field",
        "surface": "stream_options.include_obfuscation",
        "status": "supported_local",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.lifecycle_text",
        "notes": "Respawn validates stream_options and emits obfuscation fields on text delta events by default. include_obfuscation=false suppresses them.",
    },
    {
        "id": "request.background",
        "category": "request_field",
        "surface": "background=true",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.create_poll_complete",
        "notes": "Requires store=true; streaming background responses are rejected until streaming replay/resume is implemented.",
    },
    {
        "id": "request.background_store_requirement",
        "category": "request_field",
        "surface": "background=true with store=false",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.store_false_invalid",
        "notes": "Rejected with an OpenAI-shaped invalid_request error because background responses must be pollable.",
    },
    {
        "id": "request.sampling_and_limits",
        "category": "request_field",
        "surface": "temperature, top_p, max_output_tokens",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.blocking",
    },
    {
        "id": "request.function_tools",
        "category": "request_field",
        "surface": "tools entries with type=function",
        "status": "supported",
        "tags": ["tools"],
        "benchmark_case": "responses.tools.function_call",
        "notes": "Function tools are protocol data only; Respawn never executes them.",
    },
    {
        "id": "request.tool_choice",
        "category": "request_field",
        "surface": "tool_choice auto, none, required, forced function, and allowed_tools",
        "status": "supported_local",
        "tags": ["tools"],
        "benchmark_case": "responses.tools.tool_choice_forced_function",
        "notes": "Mapped to the configured backend where possible; required/forced choices fail with a capability error if the backend/model does not emit the requested function_call.",
    },
    {
        "id": "request.parallel_and_max_tool_calls",
        "category": "request_field",
        "surface": "parallel_tool_calls, max_tool_calls",
        "status": "supported_local",
        "tags": ["tools"],
        "benchmark_case": "responses.tools.parallel_or_capability_error",
        "notes": "Respawn validates and enforces these limits around backend output instead of silently ignoring them.",
    },
    {
        "id": "request.unsupported_tool_categories",
        "category": "request_field",
        "surface": "built-in, MCP, custom free-form, shell, apply_patch, web/file/code/computer/image/internal tools",
        "status": "unsupported",
        "tags": ["tools"],
        "benchmark_case": "responses.tools.unsupported_builtin_tools",
        "notes": "Only function tool protocol data is supported. Hosted or local tool execution remains out of scope.",
    },
    {
        "id": "request.structured_output",
        "category": "request_field",
        "surface": "response_format, text.format",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.structured_output",
    },
    {
        "id": "request.text_format",
        "category": "request_field",
        "surface": "text.format={type:text|json_object|json_schema}",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.shape.blocking_text",
    },
    {
        "id": "request.metadata",
        "category": "request_field",
        "surface": "metadata",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.shape.metadata_retrieve",
    },
    {
        "id": "request.service_tier",
        "category": "request_field",
        "surface": "service_tier",
        "status": "supported_local",
        "tags": ["core"],
        "benchmark_case": "responses.shape.metadata_retrieve",
        "notes": "Accepted and round-tripped as local metadata; it does not change local scheduling.",
    },
    {
        "id": "request.safety_identifier",
        "category": "request_field",
        "surface": "safety_identifier",
        "status": "supported_local",
        "tags": ["core"],
        "benchmark_case": "responses.shape.metadata_retrieve",
        "notes": "Accepted and round-tripped for SDK shape compatibility.",
    },
    {
        "id": "request.client_metadata",
        "category": "request_field",
        "surface": "client_metadata",
        "status": "supported_local",
        "tags": ["sdk", "state"],
        "benchmark_case": "responses.shape.metadata_retrieve",
        "notes": "Accepted as opaque client telemetry metadata for Codex/SDK compatibility; it is stored with the request snapshot but is not forwarded to the model backend or exposed on response objects.",
    },
    {
        "id": "request.prompt_templates",
        "category": "request_field",
        "surface": "prompt={id, version, variables}",
        "status": "supported_local",
        "tags": ["prompt", "state"],
        "benchmark_case": "responses.prompt.template_render",
        "notes": "Respawn supports local API-managed prompt templates under /v1/responses/prompts. Templates render instructions/input with {{variable}} placeholders before local context planning and backend calls.",
    },
    {
        "id": "request.prompt_template_errors",
        "category": "request_field",
        "surface": "missing prompt templates and missing prompt variables",
        "status": "supported_local",
        "tags": ["prompt", "state"],
        "benchmark_case": "responses.prompt.template_missing",
        "notes": "Missing templates and missing variables return deterministic OpenAI-shaped errors.",
    },
    {
        "id": "request.idempotency_key",
        "category": "request_field",
        "surface": "Idempotency-Key request header for POST requests",
        "status": "supported_local",
        "tags": ["sdk", "state"],
        "benchmark_case": "sdk.errors",
        "notes": "Single-instance in-memory replay cache. Reusing a key with a different body returns 409 idempotency_conflict.",
    },
    {
        "id": "request.prompt_cache",
        "category": "request_field",
        "surface": "prompt_cache_key, prompt_cache_retention",
        "status": "supported_local",
        "tags": ["core", "prompt"],
        "benchmark_case": "responses.prompt_cache.in_memory",
        "notes": "In-process single-instance prefix accounting with in_memory and 24h TTL semantics plus manual local invalidation.",
    },
    {
        "id": "request.reasoning",
        "category": "request_field",
        "surface": "reasoning",
        "status": "supported_local",
        "tags": ["reasoning"],
        "benchmark_case": "responses.reasoning",
        "notes": "Supports local reasoning requests, summaries, and backend-mapped effort settings subject to configured model capabilities.",
    },
    {
        "id": "request.reasoning_effort_matrix",
        "category": "request_field",
        "surface": "reasoning.effort none, minimal, low, medium, high, xhigh",
        "status": "supported_backend_capability",
        "tags": ["reasoning"],
        "benchmark_case": "responses.reasoning.effort_matrix",
        "notes": "xhigh is accepted only for models configured with reasoning-effort-xhigh and maps to the closest local backend setting where needed.",
    },
    {
        "id": "request.context_management",
        "category": "request_field",
        "surface": "context_management=[{type:compaction, compact_threshold}]",
        "status": "supported_local",
        "tags": ["context", "state"],
        "benchmark_case": "responses.context.compaction",
        "notes": "Runs deterministic local compaction when the estimated rendered context crosses compact_threshold.",
    },
    {
        "id": "request.truncation_disabled",
        "category": "request_field",
        "surface": "truncation=disabled",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.blocking",
    },
    {
        "id": "request.truncation_disabled_overflow",
        "category": "request_field",
        "surface": "truncation=disabled overflow handling",
        "status": "supported_local",
        "tags": ["context"],
        "benchmark_case": "responses.context.truncation_disabled_overflow",
        "notes": "Respawn fails with context_length_exceeded before calling the configured backend when local estimates exceed the configured context window.",
    },
    {
        "id": "request.truncation_auto",
        "category": "request_field",
        "surface": "truncation=auto",
        "status": "supported_local",
        "tags": ["context"],
        "benchmark_case": "responses.context.truncation_auto",
        "notes": "Drops earliest stored chain/input-array items until the estimated prompt fits the local model context window.",
    },
    {
        "id": "request.unsupported_fields",
        "category": "request_field",
        "surface": "user and unsupported include values",
        "status": "unsupported",
        "tags": ["state"],
        "benchmark_case": "responses.unsupported_field",
        "notes": "Unsupported request fields return explicit OpenAI-shaped errors.",
    },
    {
        "id": "request.include_input_image_url",
        "category": "request_field",
        "surface": "include=message.input_image.image_url",
        "status": "supported_local",
        "tags": ["multimodal", "state"],
        "benchmark_case": "responses.include.file_artifacts",
        "notes": "Respawn preserves input image URL/source metadata and expands a safe local artifact descriptor when requested.",
    },
    {
        "id": "request.include_output_text_logprobs",
        "category": "request_field",
        "surface": "include=message.output_text.logprobs and top_logprobs",
        "status": "supported_backend_capability",
        "tags": ["core"],
        "benchmark_case": "responses.include.unsupported_logprobs",
        "notes": "Returned only when the configured backend/model is marked with the logprobs capability and actually returns token logprobs. Ollama/gpt-oss defaults return unsupported_model_capability.",
    },
    {
        "id": "request.include_hosted_tool_expansions",
        "category": "request_field",
        "surface": "file_search/web_search/code_interpreter/computer include expansions",
        "status": "unsupported",
        "tags": ["tools"],
        "benchmark_case": "responses.include.hosted_tool_unsupported",
        "notes": "These include values are valid OpenAI values but require hosted tool execution, which Respawn deliberately does not provide.",
    },
    {
        "id": "request.future_unsupported_fields",
        "category": "request_field",
        "surface": "future-only fields without a local Respawn equivalent",
        "status": "unsupported",
        "tags": ["state"],
        "benchmark_case": "responses.shape.unsupported_user_field",
        "notes": "Known unsupported fields such as the deprecated user field fail with unsupported_parameter; unknown extra fields fail schema validation.",
    },
    {
        "id": "state.background_polling",
        "category": "state",
        "surface": "background response create, retrieve polling, and terminal output persistence",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.create_poll_complete",
    },
    {
        "id": "state.background_terminal_retrieve",
        "category": "state",
        "surface": "retrieving terminal background responses after completion or cancellation",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.retrieve_terminal",
    },
    {
        "id": "state.background_cancellation",
        "category": "state",
        "surface": "queued and in-flight background response cancellation",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.cancel",
        "notes": "Cancellation is best-effort for an already running Ollama request and terminal state is persisted locally.",
    },
    {
        "id": "state.background_timeout",
        "category": "state",
        "surface": "background job timeout to failed response status",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.timeout",
        "notes": "Deterministically exercised by the mock benchmark/test suite; the real Ollama benchmark validates the HTTP path without forcing hardware-dependent slowness.",
    },
    {
        "id": "state.context_compaction_records",
        "category": "state",
        "surface": "stored context compaction event records with source item provenance",
        "status": "supported_local",
        "tags": ["context", "state"],
        "benchmark_case": "responses.context.compaction",
    },
    {
        "id": "state.context_truncation_records",
        "category": "state",
        "surface": "stored context truncation event records with before/after token estimates",
        "status": "supported_local",
        "tags": ["context", "state"],
        "benchmark_case": "responses.context.truncation_auto",
    },
    {
        "id": "state.response_artifacts",
        "category": "state",
        "surface": "stored local response artifacts for input_image/input_file parts",
        "status": "supported_local",
        "tags": ["multimodal", "state"],
        "benchmark_case": "responses.include.file_artifacts",
        "notes": "Artifact records store tenant-scoped metadata and extracted text references for multimodal inputs without duplicating large binary payloads in include expansions.",
    },
    {
        "id": "state.response_artifact_pagination",
        "category": "state",
        "surface": "response artifact metadata pagination with after, before, limit, order, first_id, last_id, has_more",
        "status": "supported_local",
        "tags": ["multimodal", "state"],
        "benchmark_case": "responses.include.annotations",
    },
    {
        "id": "state.platform_objects_tenant_scope",
        "category": "state",
        "surface": "local platform files are tenant-scoped and unavailable across tenants",
        "status": "supported_local",
        "tags": ["files", "state"],
        "benchmark_case": "platform_objects.tenant_scope",
        "notes": "File retrieval and Responses file_id resolution both require the owning tenant.",
    },
    {
        "id": "state.compaction_followup_memory",
        "category": "state",
        "surface": "follow-up Responses requests can use local compaction items as compressed context",
        "status": "supported_local",
        "tags": ["context", "state"],
        "benchmark_case": "responses.compact.followup_memory",
        "notes": "Respawn can decode compaction items it created locally and injects their summary into the backend prompt.",
    },
    {
        "id": "io.text_messages",
        "category": "input_output",
        "surface": "message items with input_text/output_text",
        "status": "supported_text_only",
        "tags": ["core"],
        "benchmark_case": "responses.input_message_list",
    },
    {
        "id": "io.function_call_items",
        "category": "input_output",
        "surface": "function_call output items and function_call_output input items",
        "status": "supported",
        "tags": ["tools", "state"],
        "benchmark_case": "responses.tools.client_output_followup",
        "notes": "Protocol items are stored and replayed without local execution.",
    },
    {
        "id": "io.legacy_tool_result_unsupported",
        "category": "input_output",
        "surface": "legacy tool_result items",
        "status": "unsupported",
        "tags": ["tools", "state"],
        "benchmark_case": "responses.tools.unsupported_builtin_tools",
        "notes": "Only current Responses function_call/function_call_output items are accepted.",
    },
    {
        "id": "state.function_tool_item_storage",
        "category": "state",
        "surface": "stored function_call and function_call_output response items",
        "status": "supported",
        "tags": ["tools", "state"],
        "benchmark_case": "responses.tools.retrieve_function_call",
    },
    {
        "id": "state.function_tool_previous_response_replay",
        "category": "state",
        "surface": "previous_response_id replay for function_call/function_call_output turns",
        "status": "supported",
        "tags": ["tools", "state"],
        "benchmark_case": "responses.tools.previous_response_replay",
    },
    {
        "id": "state.function_tool_input_item_listing",
        "category": "state",
        "surface": "GET /v1/responses/{id}/input_items for function_call_output items",
        "status": "supported",
        "tags": ["tools", "state"],
        "benchmark_case": "responses.tools.input_items_function_output",
    },
    {
        "id": "io.reasoning_items",
        "category": "input_output",
        "surface": "reasoning input/output items",
        "status": "supported_local",
        "tags": ["reasoning"],
        "benchmark_case": "responses.reasoning",
    },
    {
        "id": "io.reasoning_encrypted_content",
        "category": "input_output",
        "surface": "reasoning.encrypted_content include and reasoning item encrypted_content",
        "status": "supported_local",
        "tags": ["reasoning", "state"],
        "benchmark_case": "responses.reasoning.encrypted_roundtrip",
        "notes": "Respawn emits local opaque encrypted-content envelopes when include contains reasoning.encrypted_content and preserves client-supplied reasoning encrypted_content input items.",
    },
    {
        "id": "io.compaction_items",
        "category": "input_output",
        "surface": "compaction input/output items with encrypted_content",
        "status": "supported_local",
        "tags": ["context", "state"],
        "benchmark_case": "responses.context.compaction",
        "notes": "Compaction items are opaque to clients. Respawn can decode locally generated items for subsequent local context replay.",
    },
    {
        "id": "io.input_image",
        "category": "input_output",
        "surface": "input_image content parts from URL or data URL/base64",
        "status": "supported_backend_capability",
        "tags": ["multimodal"],
        "benchmark_case": "responses.multimodal.input_image_vision",
        "notes": "Mapped to Ollama native images arrays when the selected model is configured with the vision capability.",
    },
    {
        "id": "io.input_image_capability_errors",
        "category": "input_output",
        "surface": "input_image with a text-only model",
        "status": "supported",
        "tags": ["multimodal"],
        "benchmark_case": "responses.multimodal.input_image_unsupported_model",
        "notes": "Valid image request shapes fail with unsupported_model_capability when the selected model lacks vision.",
    },
    {
        "id": "io.input_file",
        "category": "input_output",
        "surface": "input_file content parts from URL or data URL/base64 with text/PDF extraction",
        "status": "supported_local",
        "tags": ["multimodal"],
        "benchmark_case": "responses.multimodal.input_file_text",
        "notes": "Respawn extracts text before the backend call for text, Markdown, JSON, CSV/TSV, code files, and PDFs.",
    },
    {
        "id": "io.input_file_file_id",
        "category": "input_output",
        "surface": "input_file.file_id referencing local Files API uploads",
        "status": "supported_local",
        "tags": ["files", "multimodal"],
        "benchmark_case": "responses.input_file.file_id",
        "notes": "Uploaded user_data/assistants files are resolved through the tenant-scoped local Files API and extracted before backend generation.",
    },
    {
        "id": "io.input_file_limits",
        "category": "input_output",
        "surface": "input_file MIME/extension, size, and download errors",
        "status": "supported",
        "tags": ["multimodal"],
        "benchmark_case": "responses.multimodal.file_limits",
    },
    {
        "id": "io.output_text_file_annotations",
        "category": "input_output",
        "surface": "output_text annotations for local input_file citations",
        "status": "supported_local",
        "tags": ["multimodal", "state"],
        "benchmark_case": "responses.include.annotations",
        "notes": "When a response uses local input_file extraction, output_text carries OpenAI-shaped file_citation annotations pointing at local response artifact IDs.",
    },
    {
        "id": "io.input_audio_unsupported",
        "category": "input_output",
        "surface": "input_audio",
        "status": "unsupported",
        "tags": ["multimodal"],
        "benchmark_case": "responses.multimodal.input_audio_unsupported",
        "notes": "Audio remains a deliberate local exclusion until a dedicated audio/realtime/transcription phase exists.",
    },
    {
        "id": "io.built_in_tool_items",
        "category": "input_output",
        "surface": "built-in tool call output items",
        "status": "unsupported",
        "tags": ["tools"],
        "benchmark_case": "responses.tools.unsupported_builtin_tools",
        "notes": "Built-in/internal tool execution remains out of scope even after function-tool protocol support.",
    },
    {
        "id": "response.core_shape",
        "category": "response_object",
        "surface": "id, object, created_at, status, model, output, output_text, usage, metadata, error, incomplete_details",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.blocking",
    },
    {
        "id": "response.background_shape",
        "category": "response_object",
        "surface": "background flag, queued/in_progress/completed/failed/cancelled lifecycle states",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.retrieve_terminal",
    },
    {
        "id": "response.request_settings",
        "category": "response_object",
        "surface": "input, instructions, max_output_tokens, previous_response_id, service_tier, store, temperature, text, top_p, truncation, tools, tool_choice, max_tool_calls, parallel_tool_calls",
        "status": "supported",
        "tags": ["core", "state"],
        "benchmark_case": "responses.shape.blocking_text",
    },
    {
        "id": "response.output_content_shape",
        "category": "response_object",
        "surface": "output text content includes annotations and logprobs arrays",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.shape.blocking_text",
    },
    {
        "id": "response.output_text_logprobs",
        "category": "response_object",
        "surface": "output_text.logprobs populated from backend token logprobs",
        "status": "supported_backend_capability",
        "tags": ["core"],
        "benchmark_case": "responses.include.unsupported_logprobs",
        "notes": "Respawn stores and retrieves backend-provided logprobs, and fails explicitly when the configured backend/model cannot provide them.",
    },
    {
        "id": "response.incomplete_status",
        "category": "response_object",
        "surface": "status=incomplete with incomplete_details.reason when max output exhaustion is detectable",
        "status": "supported_local",
        "tags": ["core"],
        "benchmark_case": "responses.shape.max_output_incomplete",
    },
    {
        "id": "response.compaction_object",
        "category": "response_object",
        "surface": "response.compaction object from POST /v1/responses/compact",
        "status": "supported_local",
        "tags": ["context", "state"],
        "benchmark_case": "responses.compact",
    },
    {
        "id": "response.cached_tokens",
        "category": "response_object",
        "surface": "usage.input_tokens_details.cached_tokens",
        "status": "supported_local",
        "tags": ["core", "prompt"],
        "benchmark_case": "responses.prompt_cache.in_memory",
    },
    {
        "id": "response.reasoning_tokens",
        "category": "response_object",
        "surface": "usage.output_tokens_details.reasoning_tokens",
        "status": "supported_local",
        "tags": ["reasoning"],
        "benchmark_case": "responses.reasoning",
    },
    {
        "id": "response.reasoning_summary",
        "category": "response_object",
        "surface": "reasoning output item summary array",
        "status": "supported_local",
        "tags": ["reasoning"],
        "benchmark_case": "responses.reasoning.summary",
        "notes": "Summary text is generated by a deterministic local provider and does not expose raw backend thinking text.",
    },
    {
        "id": "state.reasoning_previous_response_carryover",
        "category": "state",
        "surface": "stored reasoning items through previous_response_id chains",
        "status": "supported_local",
        "tags": ["reasoning", "state"],
        "benchmark_case": "responses.reasoning.previous_response_carryover",
    },
    {
        "id": "streaming.text_lifecycle",
        "category": "streaming_event",
        "surface": "response.created, response.in_progress, response.output_item.added, response.content_part.added, response.output_text.delta, response.output_text.done, response.content_part.done, response.output_item.done, response.completed or response.incomplete",
        "status": "supported",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.lifecycle_text",
    },
    {
        "id": "streaming.event_sequence_and_sse_id",
        "category": "streaming_event",
        "surface": "SSE id plus per-event sequence_number",
        "status": "supported_local",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.lifecycle_text",
    },
    {
        "id": "streaming.reasoning_summary",
        "category": "streaming_event",
        "surface": "response.reasoning_summary_part.added, response.reasoning_summary_text.delta, response.reasoning_summary_text.done, response.reasoning_summary_part.done",
        "status": "supported_local",
        "tags": ["streaming", "reasoning"],
        "benchmark_case": "responses.stream.reasoning",
    },
    {
        "id": "streaming.incomplete",
        "category": "streaming_event",
        "surface": "response.incomplete terminal event when max-output exhaustion is detectable",
        "status": "supported_local",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.incomplete",
    },
    {
        "id": "streaming.failure",
        "category": "streaming_event",
        "surface": "response.failed, error",
        "status": "supported",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.failure",
    },
    {
        "id": "streaming.sdk_parse",
        "category": "sdk_contract",
        "surface": "official OpenAI Python SDK stream parser",
        "status": "supported",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.sdk_parse",
    },
    {
        "id": "sdk.python_create_retrieve_delete",
        "category": "sdk_contract",
        "surface": "official OpenAI Python SDK Responses create, retrieve, input_items list, delete, and Files create/list/content/delete",
        "status": "supported",
        "tags": ["sdk", "core", "state"],
        "benchmark_case": "sdk.responses.create_retrieve_delete",
    },
    {
        "id": "sdk.request_id_headers",
        "category": "sdk_contract",
        "surface": "x-request-id response headers and SDK _request_id parsing",
        "status": "supported",
        "tags": ["sdk", "observability"],
        "benchmark_case": "sdk.responses.create_retrieve_delete",
    },
    {
        "id": "sdk.python_stream",
        "category": "sdk_contract",
        "surface": "official OpenAI Python SDK Responses stream helper",
        "status": "supported",
        "tags": ["sdk", "streaming"],
        "benchmark_case": "sdk.responses.stream",
    },
    {
        "id": "sdk.python_background",
        "category": "sdk_contract",
        "surface": "official OpenAI Python SDK background create, retrieve, and cancel",
        "status": "supported",
        "tags": ["sdk", "background", "state"],
        "benchmark_case": "sdk.responses.background",
    },
    {
        "id": "sdk.python_errors",
        "category": "sdk_contract",
        "surface": "official OpenAI Python SDK exception classes for 400, 404, 409, 422, and backend/server errors",
        "status": "supported",
        "tags": ["sdk", "state"],
        "benchmark_case": "sdk.errors",
    },
    {
        "id": "streaming.function_call_arguments",
        "category": "streaming_event",
        "surface": "response.function_call_arguments.delta, response.function_call_arguments.done",
        "status": "supported",
        "tags": ["streaming", "tools"],
        "benchmark_case": "responses.tools.stream_arguments",
    },
    {
        "id": "observability.metrics",
        "category": "observability",
        "surface": "/metrics gateway, model, token, and Ollama signals",
        "status": "supported",
        "tags": ["observability"],
        "benchmark_case": "metrics",
    },
    {
        "id": "observability.background_metrics",
        "category": "observability",
        "surface": "background job counters, running gauge, and latency histogram",
        "status": "supported",
        "tags": ["background", "observability"],
        "benchmark_case": "metrics.background_jobs",
    },
    {
        "id": "observability.function_tool_metrics",
        "category": "observability",
        "surface": "function tool protocol request/call/output/unsupported/capability counters",
        "status": "supported",
        "tags": ["tools", "observability"],
        "benchmark_case": "metrics.function_tools",
    },
    {
        "id": "observability.reasoning_metrics",
        "category": "observability",
        "surface": "reasoning request, token, and heavy-request counters",
        "status": "supported_local",
        "tags": ["reasoning", "observability"],
        "benchmark_case": "metrics.reasoning",
    },
    {
        "id": "observability.context_metrics",
        "category": "observability",
        "surface": "context compaction, truncation, overflow, token before/after, and compression ratio metrics",
        "status": "supported_local",
        "tags": ["context", "observability"],
        "benchmark_case": "metrics.context_management",
    },
    {
        "id": "observability.include_metrics",
        "category": "observability",
        "surface": "include expansion counters, byte counters, and capability-error counters",
        "status": "supported_local",
        "tags": ["observability"],
        "benchmark_case": "metrics.include_expansions",
    },
    {
        "id": "observability.prompt_cache_metrics",
        "category": "observability",
        "surface": "prompt template operation counters and local prompt-cache hit ratio/token counters",
        "status": "supported_local",
        "tags": ["prompt", "observability"],
        "benchmark_case": "metrics.prompt_cache",
    },
    {
        "id": "observability.full_surface_metrics",
        "category": "observability",
        "surface": "endpoint, feature-family, status, token-kind, backend-model, job-status, cache, storage, readiness, idempotency, and operational failure metrics",
        "status": "supported_local",
        "tags": ["observability", "ops"],
        "benchmark_case": "metrics.full_surface",
    },
    {
        "id": "ops.readiness_checks",
        "category": "operations",
        "surface": "GET /readyz checks database, Ollama/backend, worker, cache, and storage readiness",
        "status": "supported_local",
        "tags": ["ops", "observability"],
        "benchmark_case": "readyz",
    },
    {
        "id": "ops.ollama_unavailable",
        "category": "operations",
        "surface": "Ollama/backend outage visibility through OpenAI-shaped 5xx errors, backend metrics, and operational failure metrics",
        "status": "supported_local",
        "tags": ["ops", "observability"],
        "benchmark_case": "ops.ollama_unavailable",
    },
    {
        "id": "ops.concurrent_streaming",
        "category": "operations",
        "surface": "single-instance concurrent Responses streaming isolation",
        "status": "supported_local",
        "tags": ["ops", "streaming"],
        "benchmark_case": "ops.concurrent_streaming",
    },
    {
        "id": "ops.concurrent_background",
        "category": "operations",
        "surface": "single-instance concurrent background job isolation",
        "status": "supported_local",
        "tags": ["ops", "background"],
        "benchmark_case": "ops.concurrent_background",
    },
    {
        "id": "ops.release_certification",
        "category": "operations",
        "surface": "compatibility release certification through manifest coverage gate and release checklist",
        "status": "supported_local",
        "tags": ["ops", "observability"],
        "benchmark_case": "compatibility.coverage",
    },
    {
        "id": "benchmark.history_compare",
        "category": "operations",
        "surface": "benchmark report comparison against a previous JSON report",
        "status": "supported_local",
        "tags": ["benchmark", "ops"],
        "benchmark_case": "benchmark.history_compare",
    },
]


def compatibility_manifest() -> dict[str, Any]:
    features = [_normalize_feature(feature) for feature in FEATURES]
    return {
        "object": "respawn.responses_compatibility_manifest",
        "version": MANIFEST_VERSION,
        "source": MANIFEST_SOURCE,
        "features": features,
        "summary": _summary(features),
    }


def manifest_summary() -> dict[str, Any]:
    return compatibility_manifest()["summary"]


def _normalize_feature(feature: dict[str, Any]) -> dict[str, Any]:
    normalized = dict(feature)
    normalized.setdefault("notes", "")
    normalized.setdefault("benchmark_case", None)
    normalized["benchmark_required"] = _benchmark_required(normalized)
    return normalized


def _benchmark_required(feature: dict[str, Any]) -> bool:
    status = str(feature.get("status", ""))
    return status.startswith("supported") or bool(feature.get("benchmark_case"))


def _summary(features: list[dict[str, Any]]) -> dict[str, Any]:
    status_counts = Counter(str(feature.get("status", "unknown")) for feature in features)
    category_counts = Counter(str(feature.get("category", "unknown")) for feature in features)
    supported = [feature for feature in features if str(feature.get("status", "")).startswith("supported")]
    unsupported = [feature for feature in features if str(feature.get("status", "")) == "unsupported"]
    return {
        "total": len(features),
        "supported": len(supported),
        "unsupported": len(unsupported),
        "by_status": dict(sorted(status_counts.items())),
        "by_category": dict(sorted(category_counts.items())),
    }
