from __future__ import annotations

from collections import Counter
from typing import Any


MANIFEST_VERSION = "phase-8"
MANIFEST_SOURCE = "docs/RESPONSES_COMPATIBILITY.md"


FEATURES: list[dict[str, Any]] = [
    {
        "id": "endpoints.responses.create",
        "category": "endpoint",
        "surface": "POST /v1/responses",
        "status": "supported",
        "tags": ["core", "state"],
        "benchmark_case": "responses.blocking",
    },
    {
        "id": "endpoints.responses.retrieve",
        "category": "endpoint",
        "surface": "GET /v1/responses/{response_id}",
        "status": "supported",
        "tags": ["core", "state"],
        "benchmark_case": "responses.retrieve",
    },
    {
        "id": "endpoints.responses.delete",
        "category": "endpoint",
        "surface": "DELETE /v1/responses/{response_id}",
        "status": "supported",
        "tags": ["core", "state"],
        "benchmark_case": "responses.delete",
    },
    {
        "id": "endpoints.responses.input_items",
        "category": "endpoint",
        "surface": "GET /v1/responses/{response_id}/input_items",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.input_items",
    },
    {
        "id": "state.input_item_storage",
        "category": "state",
        "surface": "stored response input items with stable item IDs and original order",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.items.input_storage",
    },
    {
        "id": "state.input_item_pagination",
        "category": "state",
        "surface": "input item pagination with after, before, limit, order, first_id, last_id, has_more",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.items.pagination_after",
    },
    {
        "id": "state.input_items_store_false_hidden",
        "category": "state",
        "surface": "store=false responses do not expose input item lists",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.items.store_false_hidden",
    },
    {
        "id": "state.input_items_tenant_scope",
        "category": "state",
        "surface": "stored input item lists are tenant-scoped",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.items.tenant_scope",
    },
    {
        "id": "endpoints.responses.input_tokens",
        "category": "endpoint",
        "surface": "POST /v1/responses/input_tokens",
        "status": "supported_estimated",
        "tags": ["core"],
        "benchmark_case": "responses.input_tokens",
    },
    {
        "id": "endpoints.responses.cancel",
        "category": "endpoint",
        "surface": "POST /v1/responses/{response_id}/cancel",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.cancel",
        "notes": "Cancels background Responses jobs in the current single Respawn instance.",
    },
    {
        "id": "endpoints.responses.compact",
        "category": "endpoint",
        "surface": "POST /v1/responses/compact",
        "status": "unsupported",
        "tags": ["state"],
        "notes": "Requires compaction over stored response chains.",
    },
    {
        "id": "endpoints.chat_completions.create",
        "category": "endpoint",
        "surface": "POST /v1/chat/completions",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "chat.completions",
    },
    {
        "id": "endpoints.models.list",
        "category": "endpoint",
        "surface": "GET /v1/models",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "models",
    },
    {
        "id": "request.model_and_text_input",
        "category": "request_field",
        "surface": "model, input string, input text parts",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.blocking",
    },
    {
        "id": "request.instructions",
        "category": "request_field",
        "surface": "instructions",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.structured_output",
    },
    {
        "id": "request.previous_response_id",
        "category": "request_field",
        "surface": "previous_response_id",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.previous_response_id",
    },
    {
        "id": "request.store",
        "category": "request_field",
        "surface": "store",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.store_false",
    },
    {
        "id": "request.stream",
        "category": "request_field",
        "surface": "stream",
        "status": "supported",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.lifecycle_text",
    },
    {
        "id": "request.stream_options",
        "category": "request_field",
        "surface": "stream_options.include_obfuscation",
        "status": "supported_local",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.lifecycle_text",
        "notes": "Respawn validates stream_options and emits obfuscation fields on text delta events by default. include_obfuscation=false suppresses them.",
    },
    {
        "id": "request.background",
        "category": "request_field",
        "surface": "background=true",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.create_poll_complete",
        "notes": "Requires store=true; streaming background responses are rejected until streaming replay/resume is implemented.",
    },
    {
        "id": "request.background_store_requirement",
        "category": "request_field",
        "surface": "background=true with store=false",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.store_false_invalid",
        "notes": "Rejected with an OpenAI-shaped invalid_request error because background responses must be pollable.",
    },
    {
        "id": "request.sampling_and_limits",
        "category": "request_field",
        "surface": "temperature, top_p, max_output_tokens",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.blocking",
    },
    {
        "id": "request.function_tools",
        "category": "request_field",
        "surface": "tools entries with type=function",
        "status": "supported",
        "tags": ["tools"],
        "benchmark_case": "responses.tools.function_call",
        "notes": "Function tools are protocol data only; Respawn never executes them.",
    },
    {
        "id": "request.tool_choice",
        "category": "request_field",
        "surface": "tool_choice auto, none, required, forced function, and allowed_tools",
        "status": "supported_local",
        "tags": ["tools"],
        "benchmark_case": "responses.tools.tool_choice_forced_function",
        "notes": "Mapped to the configured backend where possible; required/forced choices fail with a capability error if the backend/model does not emit the requested function_call.",
    },
    {
        "id": "request.parallel_and_max_tool_calls",
        "category": "request_field",
        "surface": "parallel_tool_calls, max_tool_calls",
        "status": "supported_local",
        "tags": ["tools"],
        "benchmark_case": "responses.tools.parallel_or_capability_error",
        "notes": "Respawn validates and enforces these limits around backend output instead of silently ignoring them.",
    },
    {
        "id": "request.unsupported_tool_categories",
        "category": "request_field",
        "surface": "built-in, MCP, custom free-form, shell, apply_patch, web/file/code/computer/image/internal tools",
        "status": "unsupported",
        "tags": ["tools"],
        "benchmark_case": "responses.tools.unsupported_builtin_tools",
        "notes": "Only function tool protocol data is supported. Hosted or local tool execution remains out of scope.",
    },
    {
        "id": "request.structured_output",
        "category": "request_field",
        "surface": "response_format, text.format",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.structured_output",
    },
    {
        "id": "request.text_format",
        "category": "request_field",
        "surface": "text.format={type:text|json_object|json_schema}",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.shape.blocking_text",
    },
    {
        "id": "request.metadata",
        "category": "request_field",
        "surface": "metadata",
        "status": "supported",
        "tags": ["state"],
        "benchmark_case": "responses.shape.metadata_retrieve",
    },
    {
        "id": "request.service_tier",
        "category": "request_field",
        "surface": "service_tier",
        "status": "supported_local",
        "tags": ["core"],
        "benchmark_case": "responses.shape.metadata_retrieve",
        "notes": "Accepted and round-tripped as local metadata; it does not change local scheduling.",
    },
    {
        "id": "request.safety_identifier",
        "category": "request_field",
        "surface": "safety_identifier",
        "status": "supported_local",
        "tags": ["core"],
        "benchmark_case": "responses.shape.metadata_retrieve",
        "notes": "Accepted and round-tripped for SDK shape compatibility.",
    },
    {
        "id": "request.prompt_cache",
        "category": "request_field",
        "surface": "prompt_cache_key, prompt_cache_retention",
        "status": "supported_local",
        "tags": ["core"],
        "benchmark_case": "responses.prompt_cache",
    },
    {
        "id": "request.reasoning",
        "category": "request_field",
        "surface": "reasoning",
        "status": "supported_local",
        "tags": ["reasoning"],
        "benchmark_case": "responses.reasoning",
    },
    {
        "id": "request.truncation_disabled",
        "category": "request_field",
        "surface": "truncation=disabled",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.blocking",
    },
    {
        "id": "request.unsupported_fields",
        "category": "request_field",
        "surface": "include, context_management, prompt, top_logprobs, user",
        "status": "unsupported",
        "tags": ["state"],
        "benchmark_case": "responses.unsupported_field",
        "notes": "Unsupported request fields return explicit OpenAI-shaped errors.",
    },
    {
        "id": "request.future_unsupported_fields",
        "category": "request_field",
        "surface": "future-only fields such as truncation=auto",
        "status": "unsupported",
        "tags": ["state"],
        "benchmark_case": "responses.shape.unsupported_future_field",
        "notes": "Accepted Phase 1 fields are handled explicitly; deferred fields still fail with unsupported_parameter.",
    },
    {
        "id": "state.background_polling",
        "category": "state",
        "surface": "background response create, retrieve polling, and terminal output persistence",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.create_poll_complete",
    },
    {
        "id": "state.background_terminal_retrieve",
        "category": "state",
        "surface": "retrieving terminal background responses after completion or cancellation",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.retrieve_terminal",
    },
    {
        "id": "state.background_cancellation",
        "category": "state",
        "surface": "queued and in-flight background response cancellation",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.cancel",
        "notes": "Cancellation is best-effort for an already running Ollama request and terminal state is persisted locally.",
    },
    {
        "id": "state.background_timeout",
        "category": "state",
        "surface": "background job timeout to failed response status",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.timeout",
        "notes": "Deterministically exercised by the mock benchmark/test suite; the real Ollama benchmark validates the HTTP path without forcing hardware-dependent slowness.",
    },
    {
        "id": "io.text_messages",
        "category": "input_output",
        "surface": "message items with input_text/output_text",
        "status": "supported_text_only",
        "tags": ["core"],
        "benchmark_case": "responses.input_message_list",
    },
    {
        "id": "io.function_call_items",
        "category": "input_output",
        "surface": "function_call output items and function_call_output input items",
        "status": "supported",
        "tags": ["tools", "state"],
        "benchmark_case": "responses.tools.client_output_followup",
        "notes": "Protocol items are stored and replayed without local execution.",
    },
    {
        "id": "io.legacy_tool_result_unsupported",
        "category": "input_output",
        "surface": "legacy tool_result items",
        "status": "unsupported",
        "tags": ["tools", "state"],
        "benchmark_case": "responses.tools.unsupported_builtin_tools",
        "notes": "Only current Responses function_call/function_call_output items are accepted.",
    },
    {
        "id": "state.function_tool_item_storage",
        "category": "state",
        "surface": "stored function_call and function_call_output response items",
        "status": "supported",
        "tags": ["tools", "state"],
        "benchmark_case": "responses.tools.retrieve_function_call",
    },
    {
        "id": "state.function_tool_previous_response_replay",
        "category": "state",
        "surface": "previous_response_id replay for function_call/function_call_output turns",
        "status": "supported",
        "tags": ["tools", "state"],
        "benchmark_case": "responses.tools.previous_response_replay",
    },
    {
        "id": "state.function_tool_input_item_listing",
        "category": "state",
        "surface": "GET /v1/responses/{id}/input_items for function_call_output items",
        "status": "supported",
        "tags": ["tools", "state"],
        "benchmark_case": "responses.tools.input_items_function_output",
    },
    {
        "id": "io.reasoning_items",
        "category": "input_output",
        "surface": "reasoning input/output items",
        "status": "supported_local",
        "tags": ["reasoning"],
        "benchmark_case": "responses.reasoning",
    },
    {
        "id": "io.input_image",
        "category": "input_output",
        "surface": "input_image content parts from URL or data URL/base64",
        "status": "supported_backend_capability",
        "tags": ["multimodal"],
        "benchmark_case": "responses.multimodal.input_image_vision",
        "notes": "Mapped to Ollama native images arrays when the selected model is configured with the vision capability.",
    },
    {
        "id": "io.input_image_capability_errors",
        "category": "input_output",
        "surface": "input_image with a text-only model",
        "status": "supported",
        "tags": ["multimodal"],
        "benchmark_case": "responses.multimodal.input_image_unsupported_model",
        "notes": "Valid image request shapes fail with unsupported_model_capability when the selected model lacks vision.",
    },
    {
        "id": "io.input_file",
        "category": "input_output",
        "surface": "input_file content parts from URL or data URL/base64 with text/PDF extraction",
        "status": "supported_local",
        "tags": ["multimodal"],
        "benchmark_case": "responses.multimodal.input_file_text",
        "notes": "Respawn extracts text before the backend call for text, Markdown, JSON, CSV/TSV, code files, and PDFs.",
    },
    {
        "id": "io.input_file_limits",
        "category": "input_output",
        "surface": "input_file MIME/extension, size, and download errors",
        "status": "supported",
        "tags": ["multimodal"],
        "benchmark_case": "responses.multimodal.file_limits",
    },
    {
        "id": "io.input_audio_unsupported",
        "category": "input_output",
        "surface": "input_audio",
        "status": "unsupported",
        "tags": ["multimodal"],
        "benchmark_case": "responses.multimodal.input_audio_unsupported",
        "notes": "Audio remains a deliberate local exclusion until a dedicated audio/realtime/transcription phase exists.",
    },
    {
        "id": "io.built_in_tool_items",
        "category": "input_output",
        "surface": "built-in tool call output items",
        "status": "unsupported",
        "tags": ["tools"],
        "benchmark_case": "responses.tools.unsupported_builtin_tools",
        "notes": "Built-in/internal tool execution remains out of scope even after function-tool protocol support.",
    },
    {
        "id": "response.core_shape",
        "category": "response_object",
        "surface": "id, object, created_at, status, model, output, output_text, usage, metadata, error, incomplete_details",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.blocking",
    },
    {
        "id": "response.background_shape",
        "category": "response_object",
        "surface": "background flag, queued/in_progress/completed/failed/cancelled lifecycle states",
        "status": "supported",
        "tags": ["background", "state"],
        "benchmark_case": "responses.background.retrieve_terminal",
    },
    {
        "id": "response.request_settings",
        "category": "response_object",
        "surface": "input, instructions, max_output_tokens, previous_response_id, service_tier, store, temperature, text, top_p, truncation, tools, tool_choice, max_tool_calls, parallel_tool_calls",
        "status": "supported",
        "tags": ["core", "state"],
        "benchmark_case": "responses.shape.blocking_text",
    },
    {
        "id": "response.output_content_shape",
        "category": "response_object",
        "surface": "output text content includes annotations and logprobs arrays",
        "status": "supported",
        "tags": ["core"],
        "benchmark_case": "responses.shape.blocking_text",
    },
    {
        "id": "response.incomplete_status",
        "category": "response_object",
        "surface": "status=incomplete with incomplete_details.reason when max output exhaustion is detectable",
        "status": "supported_local",
        "tags": ["core"],
        "benchmark_case": "responses.shape.max_output_incomplete",
    },
    {
        "id": "response.cached_tokens",
        "category": "response_object",
        "surface": "usage.input_tokens_details.cached_tokens",
        "status": "supported_local",
        "tags": ["core"],
        "benchmark_case": "responses.prompt_cache",
    },
    {
        "id": "response.reasoning_tokens",
        "category": "response_object",
        "surface": "usage.output_tokens_details.reasoning_tokens",
        "status": "supported_local",
        "tags": ["reasoning"],
        "benchmark_case": "responses.reasoning",
    },
    {
        "id": "streaming.text_lifecycle",
        "category": "streaming_event",
        "surface": "response.created, response.in_progress, response.output_item.added, response.content_part.added, response.output_text.delta, response.output_text.done, response.content_part.done, response.output_item.done, response.completed or response.incomplete",
        "status": "supported",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.lifecycle_text",
    },
    {
        "id": "streaming.event_sequence_and_sse_id",
        "category": "streaming_event",
        "surface": "SSE id plus per-event sequence_number",
        "status": "supported_local",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.lifecycle_text",
    },
    {
        "id": "streaming.reasoning_summary",
        "category": "streaming_event",
        "surface": "response.reasoning_summary_part.added, response.reasoning_summary_text.delta, response.reasoning_summary_text.done, response.reasoning_summary_part.done",
        "status": "supported_local",
        "tags": ["streaming", "reasoning"],
        "benchmark_case": "responses.stream.reasoning",
    },
    {
        "id": "streaming.incomplete",
        "category": "streaming_event",
        "surface": "response.incomplete terminal event when max-output exhaustion is detectable",
        "status": "supported_local",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.incomplete",
    },
    {
        "id": "streaming.failure",
        "category": "streaming_event",
        "surface": "response.failed, error",
        "status": "supported",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.failure",
    },
    {
        "id": "streaming.sdk_parse",
        "category": "sdk_contract",
        "surface": "official OpenAI Python SDK stream parser",
        "status": "supported",
        "tags": ["streaming"],
        "benchmark_case": "responses.stream.sdk_parse",
    },
    {
        "id": "streaming.function_call_arguments",
        "category": "streaming_event",
        "surface": "response.function_call_arguments.delta, response.function_call_arguments.done",
        "status": "supported",
        "tags": ["streaming", "tools"],
        "benchmark_case": "responses.tools.stream_arguments",
    },
    {
        "id": "observability.metrics",
        "category": "observability",
        "surface": "/metrics gateway, model, token, and Ollama signals",
        "status": "supported",
        "tags": ["observability"],
        "benchmark_case": "metrics",
    },
    {
        "id": "observability.background_metrics",
        "category": "observability",
        "surface": "background job counters, running gauge, and latency histogram",
        "status": "supported",
        "tags": ["background", "observability"],
        "benchmark_case": "metrics.background_jobs",
    },
    {
        "id": "observability.function_tool_metrics",
        "category": "observability",
        "surface": "function tool protocol request/call/output/unsupported/capability counters",
        "status": "supported",
        "tags": ["tools", "observability"],
        "benchmark_case": "metrics.function_tools",
    },
]


def compatibility_manifest() -> dict[str, Any]:
    features = [_normalize_feature(feature) for feature in FEATURES]
    return {
        "object": "respawn.responses_compatibility_manifest",
        "version": MANIFEST_VERSION,
        "source": MANIFEST_SOURCE,
        "features": features,
        "summary": _summary(features),
    }


def manifest_summary() -> dict[str, Any]:
    return compatibility_manifest()["summary"]


def _normalize_feature(feature: dict[str, Any]) -> dict[str, Any]:
    normalized = dict(feature)
    normalized.setdefault("notes", "")
    normalized.setdefault("benchmark_case", None)
    normalized["benchmark_required"] = _benchmark_required(normalized)
    return normalized


def _benchmark_required(feature: dict[str, Any]) -> bool:
    status = str(feature.get("status", ""))
    return status.startswith("supported") or bool(feature.get("benchmark_case"))


def _summary(features: list[dict[str, Any]]) -> dict[str, Any]:
    status_counts = Counter(str(feature.get("status", "unknown")) for feature in features)
    category_counts = Counter(str(feature.get("category", "unknown")) for feature in features)
    supported = [feature for feature in features if str(feature.get("status", "")).startswith("supported")]
    unsupported = [feature for feature in features if str(feature.get("status", "")) == "unsupported"]
    return {
        "total": len(features),
        "supported": len(supported),
        "unsupported": len(unsupported),
        "by_status": dict(sorted(status_counts.items())),
        "by_category": dict(sorted(category_counts.items())),
    }
