from prometheus_client import Counter, Gauge, Histogram

REQUESTS = Counter("gateway_requests_total", "Gateway HTTP requests.", ["method", "path", "status"])
REQUEST_LATENCY = Histogram("gateway_request_latency_seconds", "Gateway request latency.")
BACKEND_LATENCY = Histogram("gateway_backend_latency_seconds", "Backend request latency.")
ERRORS = Counter("gateway_errors_total", "Gateway errors.", ["code"])
TOKEN_USAGE = Counter("gateway_token_usage_total", "Token usage reported by model backends.", ["model", "kind"])
MODEL_TOKEN_USAGE = Counter("gateway_model_token_usage_total", "Token usage by API path and model.", ["api", "model", "kind"])
TOOL_EXECUTIONS = Counter("gateway_tool_executions_total", "Local tool executions.", ["tool", "status"])
RESPONSES = Counter("gateway_responses_total", "Responses API requests.", ["model", "mode", "status", "stored"])
RESPONSE_LATENCY = Histogram("gateway_response_latency_seconds", "Responses API end-to-end latency.", ["model", "mode"])
IN_FLIGHT_RESPONSES = Gauge("gateway_inflight_responses", "Responses API requests currently being processed.", ["model", "mode"])
CHAT_COMPLETIONS = Counter("gateway_chat_completions_total", "Chat completions API requests.", ["model", "mode", "status"])
CHAT_COMPLETION_LATENCY = Histogram("gateway_chat_completion_latency_seconds", "Chat completions API end-to-end latency.", ["model", "mode"])
MODEL_BACKEND_REQUESTS = Counter("gateway_backend_requests_total", "Model backend HTTP requests.", ["backend", "operation", "status"])
MODEL_BACKEND_LATENCY = Histogram("gateway_model_backend_latency_seconds", "Model backend HTTP request latency.", ["backend", "operation"])
OLLAMA_EVAL_TOKENS = Counter("gateway_ollama_eval_tokens_total", "Ollama native token counts by evaluation phase.", ["model", "operation", "phase"])
OLLAMA_EVAL_DURATION = Counter("gateway_ollama_eval_duration_seconds_total", "Ollama native evaluation duration by phase.", ["model", "operation", "phase"])
OLLAMA_EVAL_TOKENS_PER_SECOND = Gauge("gateway_ollama_eval_tokens_per_second", "Most recent Ollama native token throughput by phase.", ["model", "operation", "phase"])
